#-*- coding:utf-8 -*-
'''
Learn vocabulary

Currently a console program, don't forget to install termcolor
'''

import os.path
import random
from termcolor import colored


vocabulary = {
    #"Good morning": "ohayou gozaimasu",
    #"Good afternoon": "konnichi wa",
    #"Good evening": "konban wa",
    #"Goodnight": "oyasumi nasai",
    #"Thank you very much": "doumo arigatou gozaimasu",
    #"Thank you": "arigatou gozaimasu",
    #"Thanks": "arigatou",
    #"Cheers!": "doumo",
    #"Thank you very much": "doumo arigatou gozaimasu",
    "You're welcome": "dou itashimashite",
    #"Nice to meet you (in beginning)": "hajimemashite",
    #"Nice to meet you (thanks in advance)": "douzo yoroshiku",
    #"I'm ~": "desu",
    #"bow": "ojigi",
    #"(your) name": "onamae",
    #"What is your name?": "onamae wa nan desu ka",
    #"How are you?": "ogenki desu ka",
    #"I'm well": "genki desu",
    #"yes": "hai",
    #"no": "iie",
    #"Japan": "nihon",
    #"America": "amerika",
    #"Canada": "kanada",
    #"A person from ~": "jin",
    #"Japanese person": "nihon-jin",
    #"American person": "amerika-jin",
    #"dog": "inu",
    #"cat": "neko",
    #"apple": "ringo",
    #"water": "mizu",
    #"bird": "tori",
    #"horse": "uma",
    #"pencil": "enpitsu",
    #"pen": "pen",
    #"is/are/am": "desu",
    #"it will be": "deshou",
    #"isn't": "dewa arimasen",
    #"was": "deshita",
    #"wasn't": "dewa arimasen deshita",
    #"house": "ie",
    #"room": "heya",
    "living room": "ima",
    #"kitchen": "daidokoro",
    #"refrigerator": "reizouko",
    #"restroom (polite)": "otearai",
    #"restroom": "toire",
    #"sink": "nagashidai",
    #"bath": "ofuro",
    #"bath-room": "ofuroba",
    #"roof": "yane",
    #"ceiling": "tenjou",
    #"wall": "kabe",
    "hardwood floor": "yuka",
    #"door": "doa",
    #"window": "mado",
    #"bookshelf": "hondana",
    "chair": "isu",
    #"bed": "beddo",
    #"tatami": "tatami",
    #"sliding paper door": "shouji",
    #"futon": "futon",
    #"TV": "terebi",
    #"radio": "rajio",
    #"clock/watch": "tokei",
    #"air conditioning": "eakon",
    #"plate": "sara",
    #"bowl": "chawan",
    #"cup": "koppu",
    #"glass": "garasu",
    #"chopsticks": "ohashi",
    #"fork": "houku",
    #"spoon": "supuun",
    #"knife": "naifu",
    #"table": "teeburu",
    #"couch": "kauchi",
    #"computer": "konpyuutaa",
    #"one": "ichi",
    #"two": "ni",
    #"three": "san",
    #"four": "yon",
    #"five": "go",
    #"six": "roku",
    #"seven": "nana",
    #"eight": "hachi",
    #"nine": "kyuu",
    #"ten": "juu",
    #"one hundred": "hyaku",
    #"two hundred": "ni-hyaku",
    #"three hundred": "san-byaku",
    #"four hundred": "yon-hyaku",
    #"five hundred": "go-hyaku",
    #"six hundred": "roppyaku",
    #"seven hundred": "nana-hyaku",
    #"eight hundred": "happyaku",
    #"nine hundred": "kyuu-hyaku",
    #"one thousand": "sen",
    #"two thousand": "ni-sen",
    #"three thousand": "san-zen",
    #"four thousand": "yon-sen",
    #"five thousand": "go-sen",
    #"six thousand": "roku-sen",
    #"seven thousand": "nana-sen",
    #"eight thousand": "hassen",
    #"nine thousand": "kyuu-sen",
    #"ten thousand": "man",
    #"one hundred million": "oku",
    #"today": "kyou",
    #"yesterday": "kinou",
    #"tomorrow": "ashita",
    #"the day before yesterday": "ototoi",
    #"the day after tomorrow": "asatte",
    #"this morning": "kesa",
    "night": "yoru",
    #"last night": "yuube",
    #"Sunday": "nichiyoubi",
    #"Monday": "getsuyoubi",
    #"Tuesday": "kayoubi",
    #"Wednesday": "suiyoubi",
    #"Thursday": "mokuyoubi",
    #"Friday": "kin'youbi",
    #"Saturday": "doyoubi",
    #"last week": "senshuu",
    #"this week": "konshuu",
    #"next week": "raishuu",
    #"the week before last week": "sensenshuu",
    #"the week after next week": "saraishuu",
    #"last month": "sengetsu",
    #"this month": "kongetsu",
    #"next month": "raigetsu",
    #"the month before last": "sensengetsu",
    #"the month after next": "saraigetsu",
    #"suffix for month of year": "gatsu",
    #"January": "ichi-gatsu",
    #"February": "ni-gatsu",
    #"March": "san-gatsu",
    #"April": "shi-gatsu",
    #"July": "shichi-gatsu",
    #"September": "ku-gatsu",
    #"last year": "kyonen",
    #"this year": "kotoshi",
    #"next year": "rainen",
    #"the year before last": "ototoshi",
    #"the year after next": "sarainen",
    #"every- prefix": "mai",
    #"every day": "mainichi",
    #"every week": "maishuu",
    #"every month": "maitsuki",
    #"every year": "maitoshi",
    #"winter": "fuyu",
    #"spring": "haru",
    #"summer": "natsu",
    #"autumn": "aki",
    #"good": "ii",
    #"weather": "otenki",
    #"park": "kouen",
    #"(agreement seeker)": "ne",
    #"I'm leaving!": "itte kimasu",
    #"See you when you get home!": "itterasshai",
    #"I'm home!": "tadaima",
    #"Welcome back!": "okaeri nasai",
    #"Good night.": "oyasumi nasai",
    #"I'm sorry.": "sumimasen",
    #"Excuse me.": "shitsurei shimasu",
    #"goodbye": "sayonara",
    #"well then...": "dewa",
    #"See you later": "ja mata",
    #"Later!": "mata ne",
    #"See ya": "jaa ne",
    #"They're chopsticks": "ohashi desu",
    #"Are they chopsticks?": "ohashi desu ka",
    #"It was a dog": "inu deshita",
    #"Was it a dog?": "inu deshita ka",
    #"She's not Japanese": "nihon-jin dewa arimasen",
    #"Isn't she Japanese?": "nihon-jin dewa arimasen ka",
    #"You are American": "amerika-jin desu",
    #"Are you American?": "amerika-jin desu ka",
    #"that way / so": "sou",
    #"It is so / That's so / Yes": "sou desu",
    #"Is that so?": "sou desu ka",
    #"Oh, is that so?": "aa sou desu ka",
    #"Oh, really?": "aa sou",
    #"what": "nan",
    #"what (alternative form)": "nani",
    #"what day of the week": "nan-youbi",
    #"what month?": "nan-gatsu",
    #"What is it?": "nan desu ka",
    #"What day is it?": "nan-youbi desu ka",
    #"It's Sunday": "nichiyoubi desu",
    #"What month is it?": "nan-gatsu desu ka",
    #"It's July.": "shichi-gatsu desu",
    #"store / shop": "mise",
    #"restaurant": "resutoran",
    #"supermarket": "suupaamaaketto",
    #"supermarket (abbreviated form)": "suupaa",
    #"post office": "yuubinkyoku",
    #"train station": "eki",
    #"convenience store": "conbini",
    #"police box": "kouban",
    #"bank": "ginkou",
    #"store suffix": "ya",
    #"bookstore": "hon-ya",
    #"bread": "pan",
    #"bread store (bakery)": "pan-ya",
    #"person who works at store": "yasan",
    #"bookseller": "hon-yasan",
    #"tree": "ki",
    #"grass": "kusa",
    #"flower": "hana",
    #"river": "kawa",
    #"lake": "mizuumi",
    #"mountain": "yama",
    #"sky": "sora",
    #"sun": "taiyou",
    "cloud": "kumo",
    #"rain": "ame",
    "bicycle": "jitensha",
    #"motorized cycle": "baiku",
    #"automatic bicycle (motorcycle)": "outobai",
    #"car": "kuruma",
    #"taxi": "takushii",
    #"bus": "basu",
    #"bus stop": "basu tei",
    "train": "densha",
    #"subway": "chikatetsu",
    #"road": "mira",
    #"I / me": "watashi",
    #"you": "anata",
    #"friend": "tomodachi",
    #"person": "hito",
    #"that person / he / she": "sono shito",
    #"pluralizer": "tachi",
    #"polite name suffix": "san",
    #"teacher": "sensei",
    #"the teachers": "sensei-tachi",
    #"we": "watashi-tachi",
    #"you (plural)": "anata-tachi",
    #"people": "hito-tachi",
    #"January is winter": "ichi-gatsu wa fuyu desu",
    #"July is summer, isn't it?": "shichi-gatsu wa natsu desu ne",
    #"I am John": "watashi wa Jon desu",
    #"The name is Suzuki": "namae wa Suzuki desu",
    #"Is today Thursday?": "kyou wa mokuyoubi desu ka",
    #"Is March winter?": "san-gatsu wa fuyu desu ka",
    #"Am I a cat?": "watashi wa neko desu ka",
    #"Are you American?": "anata wa amerika-jin desu ka",
    #"food": "tabemono",
    #"japanese food": "washoku",
    #"western food": "yoshoku",
    #"sushi": "sushi",
    #"unadorned raw fish": "sashimi",
    #"japanese horseradish": "wasabi",
    "soy sauce": "shouyu",
    #"tempura": "tenpura",
    #"vinegar": "su",
    #"skewered chicken": "yakitori",
    #"chicken": "chikin",
    #"fish": "sakana",
    #"vegetables": "yasai",
    #"potato": "imo",
    #"tomato": "tomato",
    #"lettuce": "retasu",
    #"carrot": "ninjin",
    #"garlic": "ninniku",
    #"green onion": "negi",
    #"onion": "tamanegi",
    #"egg": "tamago",
    #"fruit": "kudamono",
    #"red grape": "pudou",
    "green grape": "masukanito",
    #"lemon": "remon",
    #"orange": "orenji",
    #"nectarine": "mikan",
    #"asian pear": "nashi",
    #"strawberry": "ichigo",
    #"watermelon": "suika",
    #"fast food": "fasuto fuudo",
    #"ground beef": "hanbaagu",
    #"hamburger": "hanbaagaa",
    #"French fries": "furai poteto",
    #"McDonald's": "makudonarudo",
    #"Mos Burger": "mosubaagaa",
    #"beverage": "nomimono",
    #"milk": "gyuunyuu",
    #"milkshake": "migukusenki",
    #"orange juice": "orenji juusu",
    #"lemonade": "remonedo",
    #"sake": "sake",
    #"beer": "biiru",
    #"wine": "wain",
    #"morning": "asa",
    #"noon": "hiru",
    #"evening": "ban",
    #"rice": "gohan",
    #"meal": "shokuji",
    #"breakfast": "asagohan",
    #"lunch": "hirugohan",
    #"dinner": "bangohan",
    #"like": "suki",
    #"dislike": "kirai",
    #"love (big like)": "daisuki",
    #"hate (big dislike)": "daikirai",
    #"I like ~": "ga suki desu",
    #"I dislike ~": "ga kirai desu",
    #"number one": "ichiban",
    #"My favorite is ~": "ga ichiban suki desu",
    #"I like hamburgers": "watashi wa hanbaagaa ga suki desu",
    #"Mariko dislikes sushi": "Mariko san wa sushi ga kirai desu",
    #"I don't like chicken": "chikin ga suki dewa arimasen",
    #"Don't you like beer?": "biiru ga suki dewa arimasen ka",
    #"I liked Japan": "nihon ga suki deshita",
    #"I hate carrots!": "ninjin ga daikirai desu",
    #"I really like you!": "anata ga daisuki desu",
    #"I like vegetables": "yasai ga suki desu",
    #"I like carrots the best": "ninjin ga ichiban suki desu",
    #"I like fruits": "kudamono ga suki desu",
    #"I like strawberries the most": "ichigo ga ichiban suki desu",
    #"I dislike vegetables": "yasai ga kirai desu",
    #"I hate onions the worst": "tamanegi ga ichiban kirai desu",
    #"I dislike the winter": "fuyu ga kirai desu",
    #"I hate February the most": "ni-gatsu ga ichiban kirai desu",
    #"This is not my telephone number": "kore wa watashi no denwa-bangou dewa"\
        #" arimasen",
    #"I was a student": "watashi wa gakusei deshita",
    #"He is a company employee and I am too.": "kare wa kaishain desu. watashi"\
        #" mo kaishain desu",
    #"Were you a student": "anata wa gakusei deshita ka",
    "It's close, isn't it?": "chikai desu ne",
    #"this": "kore",
    #"that": "sore",
    #"that over there": "are",
    #"which": "dore",
    #"Is this your telephone number?": "kore wa anata no denwa-bangou desu ka",
    #"Yes, this is my telephone number": "hai sore wa watashi no denwa-bangou"\
        #" desu",
    #"This X": "kono",
    #"That X": "sono",
    #"That X over there": "ano",
    #"Which X": "dono",
    "Whose family is this?": "kono hitotachi wa dare no kazoku desu ka",
    #"This telephone number is mine": "kono denwa-bangou wa watashi no desu",
    #"here": "koko",
    #"there": "soko",
    #"over there": "asoko",
    #"where": "doko",
    #"Where is your company?": "anata no kaisha wa doko ni arimasu ka",
    #"This is my telephone number": "kore wa watashi no denwa-bangou desu",
    #"Listen": "kikimasu",
    #"I'm fine (thank you)": "okage-sama de",
    #"Verb expressing the existence of inanimate objects": "aru",
    "The location where one lives": "juusho",
    #"A place of work": "kaisha",
    "Group of persons including parents, children...": "kazoku",
    #"This is a newspaper": "kore wa shinbun desu",
    #"That over there is an apple": "are wa ringo desu",
    #"That is a dog": "sore wa inu desu",
    #"Is this a flower ?": "kore wa hana desu ka",
    #"Which one is it?": "dore desu ka",
    #"Which one is the pencil?": "enpitsu wa dore desu ka",
    #"This person is a teacher.": "kono hito wa sensei desu",
    #"That teacher is Canadien": "sono sensei wa kanada-jin desu",
    #"I like that mountain": "are yama ga suki desu",
    #"Which store do you like?": "dono mise ga suki desu ka",
    #"This location (here) is America": "koko wa amerika desu",
    #"Where is it?": "doko desu ka",
    #"Where is the restaurant?": "resutoran wa doko desu ka",
    #"This kind of X": "konna",
    #"That kind of X": "sonna",
    #"That (over there) kind of X": "anna",
    #"Which kind of X": "donna",
    #"I like that kind of apple": "sonna ringo ga suki desu",
    #"What kind of person is Mariko?": "Mariko san wa donna hito desu ka",
    #"I like this kind of Sunday": "konna nichiyoubi ga suki desu",
    #"this way": "kochira",
    #"that way": "sochira",
    #"that way over there": "achira",
    #"which way?": "dochira",
    "The restroom is this way": "otearai wa kochira desu",
    #"Which way is it?": "dochira desu ka",
    #"Which way is the restaurant?": "resutoran wa dochira desu ka",
    #"student": "seito",
    "desk": "tsukue",
    "trash can": "gomibako",
    #"blackboard": "kokuban",
    #"The teacher's friend": "sensei no tomodachi",
    #"The school's teacher": "gakko no sensei",
    #"Miss Suzuki's house": "Suzuki san no ie",
    #"My cat": "watashi no neko",
    #"Your pencil": "anata no enpitsu",
    #"That's my pencil": "sore wa watashi no enpitsu desu",
    #"Is that (over there) your book?": "are wa anata no hon desu ka",
    #"Is this Mariko's pen?": "kore wa Mariko san no pen desu ka",
    #"Mr Nozaki was my teacher": "Nozaki san wa watashi no sensei deshita",
    #"Miss Suzuki, of Sony": "sony no Suzuki san",
    #"Oregon, of America": "amerika no oregon",
    #"Honda of Japan": "nihon no honda",
    #"A teacher of geography": "chiri no sensei",
    #"Mr Nozaki was my teacher of geography": "Nozaki san wa watashi no chiri "\
            #"no sensei deshita",
    #"male": "otoko",
    #"female": "onna",
    #"child": "ko",
    #"woman": "onna no hito",
    #"boy": "otoko no ko",
    #"girl": "onna no ko",
    #"Mariko is a woman": "Mariko san wa onna no hito desu",
    #"Tarou is a boy": "Tarou san wa otoko no ko desu",
    #"Is Mr. Nozaki's friend a man or a woman?": "Nozaki san no tomodachi wa "\
    #"otoko no hito desu ka. onna no hito desu ka",
    "math": "suugaku",
    "a teacher of math": "suugaku no sensei",
    #"to go": "ikimasu",
    #"to come": "kimasu",
    #"to see": "mimasu",
    #"to read": "yomimasu",
    #"to eat": "tabemasu",
    #"to drink": "nomimasu",
    #"I ate": "tabemashita",
    #"I go (regularly)": "ikimasu",
    #"Did you see?": "mimashita ka",
    #"I don't drink": "nomimasen",
    #"I didn't read": "yomimasen deshita",
    #"Won't you read?": "yomimasen ka",
    #"Won't you go?": "ikimasen ka",
    #"Won't you see?": "mimasen ka",
    #"Won't you eat? I'll eat": "tabemasen ka. tabemasu",
    #"I'll go next week": "raishuu ikimasu",
    #"I saw it last week": "senshuu mimashita",
    #"I drink everyday": "mainichi nomimasu",
    #"I won't go tomorrow": "ashita ikimasen",
    #"I didn't read last year": "kyonen yomimasen deshita",
    #"Mariko will go next year": "Mariko san wa rainen ikimasu",
    #"Last week Mrs. Suzuki read": "senshuu Suzuki san wa yomimashita",
    #"Please": "kudasai",
    #"Please do ~": "te kudasai",
    #"Please eat": "tabete kudasai",
    #"Please look": "mite kudasai",
    #"Let's ~": "mashou",
    #"Let's eat": "tabemashou",
    #"Let's drink": "nomimashou",
    #"Shall we go?": "ikimashou ka",
    #"Let's see it tomorrow": "ashita mimashou",
    #"Shall we see it next week?": "raishuu mimashou ka",
    #"to the station": "eki ni",
    #"to the park": "kouen ni",
    #"to school": "gakko ni",
    #"to your bedroom": "anata no heya ni",
    #"to Mariko's house": "Mariko san no ie ni",
    #"I went to the station": "watashi wa eki ni ikimashita",
    #"Will Mariko go to the post office?": "Mariko san wa yuubinkyoku ni ikimasu "\
        #"ka",
    #"John didn't go to school": "gakko ni Jon san wa ikimasen deshita",
    #"Tomorrow  the teacher will come to my house": "ashita sensei wa watashi "\
            #"no ie ni kimasu",
    #"Please go to school": "gakko ni itte kudasai",
    #"Please come here": "koko ni kite kudasai",
    #"Please come to my house": "watashi no ie ni kite kudasai",
    #"Where will you go?": "anata wa doko ni ikimasu ka",
    #"Where did the students go?": "gakusei-tachi wa doko ni ikimashita ka",
    #"Where shall we go tomorrow?": "ashita doko ni ikimashou ka",
    #"I will go in October": "juu-gatsu ni ikimasu",
    #"I will go to Japan in April": "shi-gatsu ni nihon ni ikimasu",
    #"I went to the station on Thursday": "mokuyoubi ni eki ni ikimashita",
    #"I don't go to school on Saturday": "doyoubi ni gakko ni ikimasen",
    #"Please give me water": "mizu wo kudasai",
    #"Please give me the cat": "neko wo kudasai",
    #"Please give me that car": "ano kuruma wo kudasai",
    #"Please give me this": "kore wo kudasai",
    #"Please give me that": "sore wo kudasai",
    #"John saw (it)": "Jon san wa mimashita",
    #"John saw a mountain": "Jon san wa yama wo mimashita",
    #"Mariko saw a car": "Mariko san wa kuruma wo mimashita",
    #"Mr Suzuki reads a book": "Suzuki san wa hon wo yomimasu",
    #"I will drink orange juice": "watashi wa orenji juusu wo nomimasu",
    #"The teacher ate this apple": "sensei wa kono ringo wo tabemashita",
    #"I will drink this water": "watashi wa kono mizu wo nomimasu",
    #"Don't you eat Japanese food?": "anata wa washoku wo tabemasen ka",
    #"I watched TV on Monday": "watashi wa getsuyoubi ni terebi wo mimashita",
    #"The student read a book last week": "seito wa senshuu hon wo "\
        #"yomimashita",
    #"That person ate sushi yesterday": "ano hito wa kinou sushi wo "\
        #"tabemashita",
    #"Did the cat eat the fish?": "neko wa sakana wo tabemashita ka",
    #"What did John eat?": "Jon san wa nani wo tabemashita ka",
    #"John ate ramen": "Jon san wa ramen wo tabemashita",
    #"What did you read?": "anata wa nani wo yomimashita ka",
    #"I read the newspaper": "shinbun wo yomimashita",
    #"What do horses eat?": "uma wa nani wo tabemasu ka",
    #"They eat grass": "kusa wo tabemasu",
    #"What will the teacher drink?": "sensei wa nani wo nomimasu ka",
    #"She'll drink beer": "biiru wo nomimasu",
    #"What did Mariko see?": "Mariko san wa nani wo mimashita ka",
    #"She saw a cat": "neko wo mimashita",
    #"yeah": "un",
    #"something": "nanika",
    #"(new information marker)": "yo",
    "I don't know/understand": "wakaranai",
    #"exists (inanimate)": "arimasu",
    #"exists (animate)": "imasu",
    #"There is a lake": "mizuumi ga arimasu",
    #"There is a bird": "tori ga imasu",
    #"There is a horse": "uma ga imasu",
    #"There is a rock": "ishi ga arimasu",
    #"rock": "ishi",
    #"There was a cat": "neko ga imashita",
    #"There is no river": "kawa ga arimasen",
    #"There were no trees": "ki ga arimasen deshita",
    #"There are birds this year": "kotoshi tori ga imasu",
    #"This river was not here last week": "senshuu kono kawa ga arimasen deshita",
    #"The teacher was here last month": "sengetsu sensei ga imashita",
    #"in Japan": "nihon ni",
    #"in America": "amerika ni",
    #"in/at my car": "watashi no kuruma ni",
    #"at school": "gakko ni",
    #"There is sushi in Japan": "nihon ni sushi ga arimasu",
    #"There are flowers in the park": "kouen ni hana ga arimasu",
    #"There are rocks over there": "ishi ga asoko ni arimasu",
    #"There is a dog in the kitchen": "daidokoro ni inu ga imasu",
    #"Where is the teacher?": "sensei wa doko ni imasu ka",
    #"The teacher is here": "sensei wa koko ni imasu",
    #"Where is Mariko?": "Mariko san wa doko ni imasu ka",
    #"Mariko is at the station": "Mariko san wa eki ni imasu",
    #"Where is the lake?": "mizuumi wa doko ni arimasu ka",
    #"Where is the school": "gakko wa doko ni arimasu ka",
    #"Where is the station?": "eki wa doko ni arimasu ka",
    #"and / with": "to",
    #"and, etc.": "ya",
    #"There are rocks, trees and rivers": "ishi to ki to kawa ga arimasu",
    #"There are rocks, trees, rivers and things like that": "ishi ya ki ya"\
        #" kawa ga arimasu",
    #"There were cats and birds, etc": "neko ya tori ga imashita",
    #"Mariko and John are here": "Mariko san to Jon san ga imasu",
    #"John went to the convenience store with Mariko": "Jon san wa Mariko san "\
        #"to conbini ni ikimashita",
    #"I ate a meal with the teacher": "watashi wa sensei to shokuji wo tabemashita",
    #"Dad / your dad": "otousan",
    #"Mom / your mom": "okaasan",
    #"my dad": "chichi",
    #"my mom": "haha",
    #"your older brother": "oniisan",
    #"your older sister": "oneesan",
    #"my older brother": "ani",
    #"my older sister": "ane",
    #"your younger brother": "otoutosan",
    #"your younger sister": "imoutosan",
    #"my younger brother": "otouto",
    #"my younger sister": "imouto",
    #"(diminuitive name suffix)": "chan",
    #"grandfather": "ojiisan",
    #"grandmother": "obaasan",
    #"grandpa": "ojiichan",
    #"grandma": "obaachan",
    #"uncle": "ojisan",
    #"aunt": "obasan",
    #"cousin": "itoko",
    #"my husband": "shujin",
    #"your husband": "goshujin",
    #"my wife": "tsuma",
    #"your wife": "okusan",
    "Where is Mom?": "okaasan wa doko ni imasu ka",
    "Dad ate dinner": "otousan wa bangohan wo tabemashita",
    "Where did Auntie go?": "obasan wa doko ni ikimashita ka",
    "Big Sister is in her room": "oneesan wa heya ni imasu",
    "My dad is in the house": "chichi wa ie ni imasu",
    "My mom went to the station": "haha wa eki ni ikimashita",
    "My little sister went to school": "imouto wa gakko ni ikimashita",
    "I like my big brother": "ani ga suki desu",
    "What is your dad's name?": "otousan wa onamae wa nan desu ka",
    "Will your mom come here today?": "kyou okaasan wa koko ni kimasu ka",
    "Did your little brother go to school yesterday": "ototousan wa kinou "
        "gakko ni ikimashita ka",
    "Where is your big sister?": "oneesan wa doko ni imasu ka",
    "Does your husband like sushi?": "goshujin wa sushi ga suki desu ka",
    "Where is your wife?": "okusan wa doko desu ka",
    "Did your husband go?": "dannasan wa ikimashita ka",
    "My wife is at college": "tsuma wa daigaku ni imasu",
    "My husband won't come today": "kyou shujin wa kimasen",
    "I like that (twenty-something) girl.": "ano oneesan ga suki desu",
    "Where did that old man go?": "ano ojiisan wa doko ni ikimashita ka",
    "he / boyfriend": "kare",
    "her / girlfriend": "kanojo",
    "Do you have a girlfriend?": "kanojo ga imasu ka",
    "I don't like my boyfriend's mom": "kare no okaasan ga suki dewa arimasen",
    "Mariko is John's girlfriend": "Mariko san wa Jon san no kanojo desu",
    "I went to the mountains with my boyfriend last week.": "senshuu "
        "kare to yama ni ikimashita",
    "hobby": "shumi",
    "interest": "kyoumi",
    "the countryside": "inaka",
    "place": "tokoro",
    "mountain climbing": "yama no bori",
    "a drive": "doraibu",
    "hiking": "haikingu",
    "a walk": "sanpo",
    "sightseeing": "kengaku",
    "What are you interested in?": "nan ni kyoumi ga arimasu ka",
    "What kind of place is it?": "donna tokoro desu ka",
    "Is it a good place?": "ii tokoro desu ka",
    "to go for a drive": "doraibu ni ikimasu",
    "welcome to": "e youkoso",
    "There you are / Go ahead / after you": "douzo",
    "number": "bangou",
    "Sorry, could you repeat that?": "sumimasen mou ichido itte kudasai",
    "hello (on phone)": "moshi moshi",
    "Now / at the moment": "ima",
    "Not at home": "rusu",
    "mobile phone": "keita denwa",
    "Have you decided?": "okimari desu ka",
    "May I have?": "wo kudasai",
    "One item": "hitotsu",
    "Two items": "utatsu",
    "Three items": "mittsu",
    "Four items": "yottsu",
    "Five items": "itsutsu",
    "Six items": "muttsu",
    "Seven items": "nanatsu",
    "Eight items": "yattsu",
    "Nine items": "kokonotsu",
    "Ten items": "tou",
    "delicious": "oishii",
    "also / as well": "mo",
    "I": "boku",
    "sandwitch": "sandoichi",
    "ham": "hamu",
    "cheese": "chizu",
    "coffee": "kouhii",
    "Mariko, what are your interests?": "Mariko san kyoumi wa nan desu ka",
    "In the summer, I like hiking. In the fall, I go on walks every day. I "\
            "like the countryside. How about you? What are your hobbies?":\
            "natsu wa haikingu ga suki desu. aki wa mainichi sanpo ni "\
            "ikimasu. inaka ga suki desu. Jon san wa shumi wa nan desu ka",
    "I like moutain climbing. I go every week.": "yama no bori ga suki desu."\
        "maishuu ikimasu",
    "the city": "tokai",
    "movie": "eiga",
    "theater": "eigakan",
    "shopping": "kaimono",
    "coffee shop": "kissaten",
    "museum": "hakubutsukan",
    "art": "bijutsu",
    "art museum": "bijutsukan",
    "karaoke": "karaoke",
    "castle": "shiro",
    "birthday": "tangyoubi",
    "party": "paatii",
    "money": "okane",
    "hall": "kan",
    "to go shopping": "kaimono ni ikimasu",
    "science museum": "kagaku hakubutsukan",
    "science": "kagaku",
    "I don't have any money": "okane ga arimasen",
    "John doesn't have any money": "Jon san wa okane ga arimasen",
    "Mariko has money.": "Mariko san wa okane ga arimasu",
    "John, do you like the city?": "Jon san tokai ga suki desu ka",
    "Yeah, I like it. I love coffee shops and karaoke.": "ee suki desu yo."\
        "kissaten ya karaoke ga daisuki desu",
    "Do you like art?": "bijutsu ga suki desu ka",
    "Yeah, I like it.": "un suki desu yo",
    "Shall we go to an art gallery or museum?": "bijutsukan ka hakubutsukan"\
        "ni ikimashou ka",
    "That sounds nice!": "ii desu ne",
    "music": "ongaku",
    "piano": "piano",
    "trumpet": "toranpetto",
    "sports": "supoutsu",
    "soccer": "sakkaa",
    "basketball": "basukettobouru",
    "American football": "futtobouru",
    "tennis": "tenisu",
    "baseball": "yakyuu",
    "I like the piano.": "piano ga suki desu",
    "I like sports.": "supoutsu ga suki desu",
    "John likes tennis": "Jon san wa tenisu ga suki desu",
}


class Question:
    """Object for a question"""

    def __init__(self, question, answer, success, failure, index):
        self.question = question
        self.answer = answer
        self.success = success
        self.failure = failure
        self.index = index

    def verify(self, answer):
        if self.answer == answer:
            self.success += 1
        else:
            self.failure += 1
        self.update_db()

    def update_db(self):
        vocab_file = open("vocabulary.txt", "w+")
        vocab_file.writelines(vocab)
        vocab_file.close()


def init():
    """At the first execution, we create a new file, where we'll add the scores
    for each sentence"""
    if not os.path.exists("vocabulary.txt"):
        vocab_file = open("vocabulary.txt", "a")
        for en_sentence, jp_sentence in vocabulary.iteritems():
            vocab_file.write("%s|%s|0|0\n" % (en_sentence, jp_sentence))
        vocab_file.close()


def question(vocab):
    line = random.choice(vocab)
    question, answer, success, failure = line.split("|")
    success = int(success)
    failure = int(failure.replace("\n", ""))
    guess = raw_input("%s (found:%s, failed:%s)\n\t%s\n%s " %
                      (colored("Question", "blue"),
                       colored(success, "green"),
                       colored(failure, "red"),
                       question,
                      colored("Answer :", "blue")))
    if guess == "x":
        return
    elif guess == answer:
        response = colored(random.choice(["Yes", "Good", "Perfect",
                                          "Congrats", "いい"]), "green")
        success += 1
    else:
        response = colored("False, the answer was '%s'" %
                           vocabulary[question], "red")
        failure += 1
    line_index = vocab.index(line)
    vocab.remove(line)
    vocab.insert(line_index, "%s|%s|%s|%s\n" % (question, answer, success,
                                                failure))
    return response


if __name__ == "__main__":
    init()
    vocab = open("vocabulary.txt").readlines()
    while 1:
        answer = question(vocab)
        if not answer:
            break
        else:
            print answer

    print "%s\nBye !%s\n" % ("~" * 10, "~" * 10)

    try:
        vocab_file = open("vocabulary.txt", "w+")
        vocab_file.writelines(vocab)
        vocab_file.close()
    except IOError, e:
        print "Couldn't save the file\n%s" % e
