#-*- coding:utf-8 -*-
'''
Learn vocabulary

Currently a console program, don't forget to install termcolor
'''

import os.path
import random
from termcolor import colored


vocabulary = {
    "Good morning": "ohayou gozaimasu",
    "Good afternoon": "konnichi wa",
    "Good evening": "konban wa",
    "Goodnight": "oyasumi nasai",
    "Thank you very much": "doumo arigatou gozaimasu",
    "Thank you": "arigatou gozaimasu",
    "Thanks": "arigatou",
    "Cheers!": "doumo",
    "You're welcome": "dou itashimashite",
    "Nice to meet you (in beginning)": "hajimemashite",
    "nice to meet you (thanks in advance)": "douzo yoroshiku",
    "i'm ~": "desu",
    "bow": "ojigi",
    "(your) name": "onamae",
    "what is your name?": "onamae wa nan desu ka",
    "how are you?": "ogenki desu ka",
    "i'm well": "genki desu",
    "yes": "hai",
    "no": "iie",
    "japan": "nihon",
    "america": "amerika",
    "canada": "kanada",
    "a person from ~": "jin",
    "japanese person": "nihonjin",
    "american person": "amerikajin",
    "dog": "inu",
    "cat": "neko",
    "apple": "ringo",
    "water": "mizu",
    "bird": "tori",
    "horse": "uma",
    "pencil": "enpitsu",
    "pen": "pen",
    "is/are/am": "desu",
    "it will be": "deshou",
    "isn't": "dewa arimasen",
    "was": "deshita",
    "wasn't": "dewa arimasen deshita",
    "house": "ie",
    "room": "heya",
    "living room": "ima",
    "kitchen": "daidokoro",
    "refrigerator": "reizouko",
    "restroom (polite)": "otearai",
    "restroom": "toire",
    "sink": "nagashidai",
    "bath": "ofuro",
    "bath-room": "ofuroba",
    "roof": "yane",
    "ceiling": "tenjou",
    "wall": "kabe",
    "hardwood floor": "yuka",
    "door": "doa",
    "window": "mado",
    "bookshelf": "hondana",
    "chair": "isu",
    "bed": "beddo",
    "tatami": "tatami",
    "sliding paper door": "shouji",
    "futon": "futon",
    "tv": "terebi",
    "radio": "rajio",
    "clock/watch": "tokei",
    "air conditioning": "eakon",
    "plate": "sara",
    "bowl": "chawan",
    "cup": "koppu",
    "glass": "garasu",
    "chopsticks": "ohashi",
    "fork": "houku",
    "spoon": "supuun",
    "knife": "naifu",
    "table": "teeburu",
    "couch": "kauchi",
    "computer": "konpyuutaa",
    "one": "ichi",
    "two": "ni",
    "three": "san",
    "four": "yon",
    "five": "go",
    "six": "roku",
    "seven": "nana",
    "eight": "hachi",
    "nine": "kyuu",
    "ten": "juu",
    "one hundred": "hyaku",
    "two hundred": "nihyaku",
    "three hundred": "sanbyaku",
    "four hundred": "yonhyaku",
    "five hundred": "gohyaku",
    "six hundred": "roppyaku",
    "seven hundred": "nanahyaku",
    "eight hundred": "happyaku",
    "nine hundred": "kyuuhyaku",
    "one thousand": "sen",
    "two thousand": "nisen",
    "three thousand": "sanzen",
    "four thousand": "yonsen",
    "five thousand": "gosen",
    "six thousand": "rokusen",
    "seven thousand": "nanasen",
    "eight thousand": "hassen",
    "nine thousand": "kyuusen",
    "ten thousand": "man",
    "one hundred million": "oku",
    "today": "kyou",
    "yesterday": "kinou",
    "tomorrow": "ashita",
    "the day before yesterday": "ototoi",
    "the day after tomorrow": "asatte",
    "this morning": "kesa",
    "night": "yoru",
    "last night": "yuube",
    "sunday": "nichiyoubi",
    "monday": "getsuyoubi",
    "tuesday": "kayoubi",
    "wednesday": "suiyoubi",
    "thursday": "mokuyoubi",
    "friday": "kin'youbi",
    "saturday": "doyoubi",
    "last week": "senshuu",
    "this week": "konshuu",
    "next week": "raishuu",
    "the week before last week": "sensenshuu",
    "the week after next week": "saraishuu",
    "last month": "sengetsu",
    "this month": "kongetsu",
    "next month": "raigetsu",
    "the month before last": "sensengetsu",
    "the month after next": "saraigetsu",
    "suffix for month of year": "gatsu",
    "january": "ichigatsu",
    "february": "nigatsu",
    "march": "sangatsu",
    "april": "shigatsu",
    "july": "shichigatsu",
    "september": "kugatsu",
    "last year": "kyonen",
    "this year": "kotoshi",
    "next year": "rainen",
    "the year before last": "ototoshi",
    "the year after next": "sarainen",
    "every- prefix": "mai",
    "every day": "mainichi",
    "every week": "maishuu",
    "every month": "maitsuki",
    "every year": "maitoshi",
    "winter": "fuyu",
    "spring": "haru",
    "summer": "natsu",
    "autumn": "aki",
    "good": "ii",
    "weather": "otenki",
    "park": "kouen",
    "(agreement seeker)": "ne",
    "i'm leaving!": "itte kimasu",
    "see you when you get home!": "itterasshai",
    "i'm home!": "tadaima",
    "welcome back!": "okaeri nasai",
    "good night.": "oyasumi nasai",
    "i'm sorry.": "sumimasen",
    "excuse me.": "shitsurei shimasu",
    "goodbye": "sayonara",
    "well then...": "dewa",
    "see you later": "ja mata",
    "later!": "mata ne",
    "see ya": "jaa ne",
    "they're chopsticks": "ohashi desu",
    "are they chopsticks?": "ohashi desu ka",
    "it was a dog": "inu deshita",
    "was it a dog?": "inu deshita ka",
    "she's not japanese": "nihonjin dewa arimasen",
    "isn't she japanese?": "nihonjin dewa arimasen ka",
    "you are american": "amerikajin desu",
    "are you american?": "amerikajin desu ka",
    "that way / so": "sou",
    "it is so / that's so / yes": "sou desu",
    "is that so?": "sou desu ka",
    "oh, is that so?": "aa sou desu ka",
    "oh, really?": "aa sou",
    "what": "nan",
    "what (alternative form)": "nani",
    "what day of the week": "nan-youbi",
    "what month?": "nangatsu",
    "what is it?": "nan desu ka",
    "what day is it?": "nan-youbi desu ka",
    "it's sunday": "nichiyoubi desu",
    "what month is it?": "nangatsu desu ka",
    "it's july.": "shichigatsu desu",
    "store / shop": "mise",
    "restaurant": "resutoran",
    "supermarket": "suupaamaaketto",
    "supermarket (abbreviated form)": "suupaa",
    "post office": "yuubinkyoku",
    "train station": "eki",
    "convenience store": "conbini",
    "police box": "kouban",
    "bank": "ginkou",
    "store suffix": "ya",
    "bookstore": "honya",
    "bread": "pan",
    "bread store (bakery)": "panya",
    "person who works at store": "yasan",
    "bookseller": "honyasan",
    "tree": "ki",
    "grass": "kusa",
    "flower": "hana",
    "river": "kawa",
    "lake": "mizuumi",
    "mountain": "yama",
    "sky": "sora",
    "sun": "taiyou",
    "cloud": "kumo",
    "rain": "ame",
    "bicycle": "jitensha",
    "motorized cycle": "baiku",
    "automatic bicycle (motorcycle)": "outobai",
    "car": "kuruma",
    "taxi": "takushii",
    "bus": "basu",
    "bus stop": "basu tei",
    "train": "densha",
    "subway": "chikatetsu",
    "road": "mira",
    "i / me": "watashi",
    "you": "anata",
    "friend": "tomodachi",
    "person": "hito",
    "that person / he / she": "sono shito",
    "pluralizer": "tachi",
    "polite name suffix": "san",
    "teacher": "sensei",
    "the teachers": "senseitachi",
    "we": "watashitachi",
    "you (plural)": "anatatachi",
    "people": "hitotachi",
    "january is winter": "ichigatsu wa fuyu desu",
    "july is summer, isn't it?": "shichigatsu wa natsu desu ne",
    "i am john": "watashi wa Jon desu",
    "the name is Suzuki": "namae wa Suzuki desu",
    "is today thursday?": "kyou wa mokuyoubi desu ka",
    "is march winter?": "sangatsu wa fuyu desu ka",
    "am i a cat?": "watashi wa neko desu ka",
    "are you american?": "anata wa amerikajin desu ka",
    "food": "tabemono",
    "japanese food": "washoku",
    "western food": "yoshoku",
    "sushi": "sushi",
    "unadorned raw fish": "sashimi",
    "japanese horseradish": "wasabi",
    "soy sauce": "shouyu",
    "tempura": "tenpura",
    "vinegar": "su",
    "skewered chicken": "yakitori",
    "chicken": "chikin",
    "fish": "sakana",
    "vegetables": "yasai",
    "potato": "imo",
    "tomato": "tomato",
    "lettuce": "retasu",
    "carrot": "ninjin",
    "garlic": "ninniku",
    "green onion": "negi",
    "onion": "tamanegi",
    "egg": "tamago",
    "fruit": "kudamono",
    "red grape": "pudou",
    "green grape": "masukanito",
    "lemon": "remon",
    "orange": "orenji",
    "nectarine": "mikan",
    "asian pear": "nashi",
    "strawberry": "ichigo",
    "watermelon": "suika",
    "fast food": "fasuto fuudo",
    "ground beef": "hanbaagu",
    "hamburger": "hanbaagaa",
    "french fries": "furai poteto",
    "mcdonald's": "makudonarudo",
    "mos burger": "mosubaagaa",
    "beverage": "nomimono",
    "milk": "gyuunyuu",
    "milkshake": "migukusenki",
    "orange juice": "orenji juusu",
    "lemonade": "remonedo",
    "sake": "sake",
    "beer": "biiru",
    "wine": "wain",
    "morning": "asa",
    "noon": "hiru",
    "evening": "ban",
    "rice": "gohan",
    "meal": "shokuji",
    "breakfast": "asagohan",
    "lunch": "hirugohan",
    "dinner": "bangohan",
    "like": "suki",
    "dislike": "kirai",
    "love (big like)": "daisuki",
    "hate (big dislike)": "daikirai",
    "i like ~": "ga suki desu",
    "i dislike ~": "ga kirai desu",
    "number one": "ichiban",
    "my favorite is ~": "ga ichiban suki desu",
    "i like hamburgers": "watashi wa hanbaagaa ga suki desu",
    "Mariko dislikes sushi": "Mariko san wa sushi ga kirai desu",
    "i don't like chicken": "chikin ga suki dewa arimasen",
    "don't you like beer?": "biiru ga suki dewa arimasen ka",
    "i liked japan": "nihon ga suki deshita",
    "i hate carrots!": "ninjin ga daikirai desu",
    "i really like you!": "anata ga daisuki desu",
    "i like vegetables": "yasai ga suki desu",
    "i like carrots the best": "ninjin ga ichiban suki desu",
    "i like fruits": "kudamono ga suki desu",
    "i like strawberries the most": "ichigo ga ichiban suki desu",
    "i dislike vegetables": "yasai ga kirai desu",
    "i hate onions the worst": "tamanegi ga ichiban kirai desu",
    "i dislike the winter": "fuyu ga kirai desu",
    "i hate february the most": "nigatsu ga ichiban kirai desu",
    "this is not my telephone number": "kore wa watashi no denwa bangou dewa"\
        " arimasen",
    "i was a student": "watashi wa gakusei deshita",
    "he is a company employee and i am too.": "kare wa kaishain desu. watashi"\
        " mo kaishain desu",
    "were you a student": "anata wa gakusei deshita ka",
    "it's close, isn't it?": "chikai desu ne",
    "this": "kore",
    "that": "sore",
    "that over there": "are",
    "which": "dore",
    "is this your telephone number?": "kore wa anata no denwa bangou desu ka",
    "yes, this is my telephone number": "hai sore wa watashi no denwa bangou"\
        " desu",
    "this x": "kono",
    "that x": "sono",
    "that x over there": "ano",
    "which x": "dono",
    "whose family is this?": "kono hitotachi wa dare no kazoku desu ka",
    "this telephone number is mine": "kono denwa bangou wa watashi no desu",
    "here": "koko",
    "there": "soko",
    "over there": "asoko",
    "where": "doko",
    "where is your company?": "anata no kaisha wa doko ni arimasu ka",
    "this is my telephone number": "kore wa watashi no denwa bangou desu",
    "listen": "kikimasu",
    "i'm fine (thank you)": "okage-sama de",
    "verb expressing the existence of inanimate objects": "aru",
    "the location where one lives": "juusho",
    "a place of work": "kaisha",
    "group of persons including parents, children...": "kazoku",
    "this is a newspaper": "kore wa shinbun desu",
    "that over there is an apple": "are wa ringo desu",
    "that is a dog": "sore wa inu desu",
    "is this a flower ?": "kore wa hana desu ka",
    "which one is it?": "dore desu ka",
    "which one is the pencil?": "enpitsu wa dore desu ka",
    "this person is a teacher.": "kono hito wa sensei desu",
    "that teacher is canadien": "sono sensei wa kanadajin desu",
    "i like that mountain": "are yama ga suki desu",
    "which store do you like?": "dono mise ga suki desu ka",
    "this location (here) is america": "koko wa amerika desu",
    "where is it?": "doko desu ka",
    "where is the restaurant?": "resutoran wa doko desu ka",
    "this kind of x": "konna",
    "that kind of x": "sonna",
    "that (over there) kind of x": "anna",
    "which kind of x": "donna",
    "i like that kind of apple": "sonna ringo ga suki desu",
    "what kind of person is Mariko?": "Mariko san wa donna hito desu ka",
    "i like this kind of sunday": "konna nichiyoubi ga suki desu",
    "this way": "kochira",
    "that way": "sochira",
    "that way over there": "achira",
    "which way?": "dochira",
    "the restroom is this way": "otearai wa kochira desu",
    "which way is it?": "dochira desu ka",
    "which way is the restaurant?": "resutoran wa dochira desu ka",
    "student": "seito",
    "desk": "tsukue",
    "trash can": "gomibako",
    "blackboard": "kokuban",
    "the teacher's friend": "sensei no tomodachi",
    "the school's teacher": "gakkou no sensei",
    "miss Suzuki's house": "Suzuki san no ie",
    "my cat": "watashi no neko",
    "your pencil": "anata no enpitsu",
    "that's my pencil": "sore wa watashi no enpitsu desu",
    "is that (over there) your book?": "are wa anata no hon desu ka",
    "is this Mariko's pen?": "kore wa Mariko san no pen desu ka",
    "mr nozaki was my teacher": "nozaki san wa watashi no sensei deshita",
    "miss Suzuki, of sony": "sony no Suzuki san",
    "oregon, of america": "amerika no oregon",
    "honda of japan": "nihon no honda",
    "a teacher of geography": "chiri no sensei",
    "mr nozaki was my teacher of geography": "nozaki san wa watashi no chiri "\
            "no sensei deshita",
    "male": "otoko",
    "female": "onna",
    "child": "ko",
    "woman": "onna no hito",
    "boy": "otoko no ko",
    "girl": "onna no ko",
    "Mariko is a woman": "Mariko san wa onna no hito desu",
    "Tarou is a boy": "Tarou san wa otoko no ko desu",
    "is mr. nozaki's friend a man or a woman?": "nozaki san no tomodachi wa "\
    "otoko no hito desu ka. onna no hito desu ka",
    "math": "suugaku",
    "a teacher of math": "suugaku no sensei",
    "to go": "ikimasu",
    "to come": "kimasu",
    "to see": "mimasu",
    "to read": "yomimasu",
    "to eat": "tabemasu",
    "to drink": "nomimasu",
    "i ate": "tabemashita",
    "i go (regularly)": "ikimasu",
    "did you see?": "mimashita ka",
    "i don't drink": "nomimasen",
    "i didn't read": "yomimasen deshita",
    "won't you read?": "yomimasen ka",
    "won't you go?": "ikimasen ka",
    "won't you see?": "mimasen ka",
    "won't you eat? i'll eat": "tabemasen ka. tabemasu",
    "i'll go next week": "raishuu ikimasu",
    "i saw it last week": "senshuu mimashita",
    "i drink everyday": "mainichi nomimasu",
    "i won't go tomorrow": "ashita ikimasen",
    "i didn't read last year": "kyonen yomimasen deshita",
    "Mariko will go next year": "Mariko san wa rainen ikimasu",
    "last week mrs. Suzuki read": "senshuu Suzuki san wa yomimashita",
    "please": "kudasai",
    "please do ~": "te kudasai",
    "please eat": "tabete kudasai",
    "please look": "mite kudasai",
    "let's ~": "mashou",
    "let's eat": "tabemashou",
    "let's drink": "nomimashou",
    "shall we go?": "ikimashou ka",
    "let's see it tomorrow": "ashita mimashou",
    "shall we see it next week?": "raishuu mimashou ka",
    "to the station": "eki ni",
    "to the park": "kouen ni",
    "to school": "gakkou ni",
    "to your bedroom": "anata no heya ni",
    "to Mariko's house": "Mariko san no ie ni",
    "i went to the station": "watashi wa eki ni ikimashita",
    "will Mariko go to the post office?": "Mariko san wa yuubinkyoku ni ikimasu "\
        "ka",
    "john didn't go to school": "gakkou ni Jon san wa ikimasen deshita",
    "tomorrow  the teacher will come to my house": "ashita sensei wa watashi "\
            "no ie ni kimasu",
    "please go to school": "gakkou ni itte kudasai",
    "please come here": "koko ni kite kudasai",
    "please come to my house": "watashi no ie ni kite kudasai",
    "where will you go?": "anata wa doko ni ikimasu ka",
    "where did the students go?": "gakuseitachi wa doko ni ikimashita ka",
    "where shall we go tomorrow?": "ashita doko ni ikimashou ka",
    "i will go in october": "juugatsu ni ikimasu",
    "i will go to japan in april": "shigatsu ni nihon ni ikimasu",
    "i went to the station on thursday": "mokuyoubi ni eki ni ikimashita",
    "i don't go to school on saturday": "doyoubi ni gakkou ni ikimasen",
    "please give me water": "mizu wo kudasai",
    "please give me the cat": "neko wo kudasai",
    "please give me that car": "ano kuruma wo kudasai",
    "please give me this": "kore wo kudasai",
    "please give me that": "sore wo kudasai",
    "john saw (it)": "Jon san wa mimashita",
    "john saw a mountain": "Jon san wa yama wo mimashita",
    "Mariko saw a car": "Mariko san wa kuruma wo mimashita",
    "mr Suzuki reads a book": "Suzuki san wa hon wo yomimasu",
    "i will drink orange juice": "watashi wa orenji juusu wo nomimasu",
    "the teacher ate this apple": "sensei wa kono ringo wo tabemashita",
    "i will drink this water": "watashi wa kono mizu wo nomimasu",
    "don't you eat japanese food?": "anata wa washoku wo tabemasen ka",
    "i watched tv on monday": "watashi wa getsuyoubi ni terebi wo mimashita",
    "the student read a book last week": "seito wa senshuu hon wo "\
        "yomimashita",
    "that person ate sushi yesterday": "ano hito wa kinou sushi wo "\
        "tabemashita",
    "did the cat eat the fish?": "neko wa sakana wo tabemashita ka",
    "what did john eat?": "Jon san wa nani wo tabemashita ka",
    "john ate ramen": "Jon san wa ramen wo tabemashita",
    "what did you read?": "anata wa nani wo yomimashita ka",
    "i read the newspaper": "shinbun wo yomimashita",
    "what do horses eat?": "uma wa nani wo tabemasu ka",
    "they eat grass": "kusa wo tabemasu",
    "what will the teacher drink?": "sensei wa nani wo nomimasu ka",
    "she'll drink beer": "biiru wo nomimasu",
    "what did Mariko see?": "Mariko san wa nani wo mimashita ka",
    "she saw a cat": "neko wo mimashita",
    "yeah": "un",
    "something": "nanika",
    "(new information marker)": "yo",
    "i don't know/understand": "wakaranai",
    "exists (inanimate)": "arimasu",
    "exists (animate)": "imasu",
    "there is a lake": "mizuumi ga arimasu",
    "there is a bird": "tori ga imasu",
    "there is a horse": "uma ga imasu",
    "there is a rock": "ishi ga arimasu",
    "rock": "ishi",
    "there was a cat": "neko ga imashita",
    "there is no river": "kawa ga arimasen",
    "there were no trees": "ki ga arimasen deshita",
    "there are birds this year": "kotoshi tori ga imasu",
    "this river was not here last week": "senshuu kono kawa ga arimasen deshita",
    "the teacher was here last month": "sengetsu sensei ga imashita",
    "in japan": "nihon ni",
    "in america": "amerika ni",
    "in/at my car": "watashi no kuruma ni",
    "at school": "gakkou ni",
    "there is sushi in japan": "nihon ni sushi ga arimasu",
    "there are flowers in the park": "kouen ni hana ga arimasu",
    "there are rocks over there": "ishi ga asoko ni arimasu",
    "there is a dog in the kitchen": "daidokoro ni inu ga imasu",
    "where is the teacher?": "sensei wa doko ni imasu ka",
    "the teacher is here": "sensei wa koko ni imasu",
    "where is Mariko?": "Mariko san wa doko ni imasu ka",
    "Mariko is at the station": "Mariko san wa eki ni imasu",
    "where is the lake?": "mizuumi wa doko ni arimasu ka",
    "where is the school": "gakkou wa doko ni arimasu ka",
    "where is the station?": "eki wa doko ni arimasu ka",
    "and / with": "to",
    "and, etc.": "ya",
    "there are rocks, trees and rivers": "ishi to ki to kawa ga arimasu",
    "there are rocks, trees, rivers and things like that": "ishi ya ki ya"\
        " kawa ga arimasu",
    "there were cats and birds, etc": "neko ya tori ga imashita",
    "Mariko and john are here": "Mariko san to Jon san ga imasu",
    "john went to the convenience store with Mariko": "Jon san wa Mariko san "\
        "to conbini ni ikimashita",
    "i ate a meal with the teacher": "watashi wa sensei to shokuji wo tabemashita",
    "dad / your dad": "otousan",
    "mom / your mom": "okaasan",
    "my dad": "chichi",
    "my mom": "haha",
    "your older brother": "oniisan",
    "your older sister": "oneesan",
    "my older brother": "ani",
    "my older sister": "ane",
    "your younger brother": "otoutosan",
    "your younger sister": "imoutosan",
    "my younger brother": "otouto",
    "my younger sister": "imouto",
    "(diminuitive name suffix)": "chan",
    "grandfather": "ojiisan",
    "grandmother": "obaasan",
    "grandpa": "ojiichan",
    "grandma": "obaachan",
    "uncle": "ojisan",
    "aunt": "obasan",
    "cousin": "itoko",
    "my husband": "shujin",
    "your husband": "goshujin",
    "my wife": "tsuma",
    "your wife": "okusan",
    "where is mom?": "okaasan wa doko ni imasu ka",
    "dad ate dinner": "otousan wa bangohan wo tabemashita",
    "where did auntie go?": "obasan wa doko ni ikimashita ka",
    "big sister is in her room": "oneesan wa heya ni imasu",
    "my dad is in the house": "chichi wa ie ni imasu",
    "my mom went to the station": "haha wa eki ni ikimashita",
    "my little sister went to school": "imouto wa gakkou ni ikimashita",
    "i like my big brother": "ani ga suki desu",
    "what is your dad's name?": "otousan wa onamae wa nan desu ka",
    "will your mom come here today?": "kyou okaasan wa koko ni kimasu ka",
    "did your little brother go to school yesterday": "ototousan wa kinou "
        "gakkou ni ikimashita ka",
    "where is your big sister?": "oneesan wa doko ni imasu ka",
    "does your husband like sushi?": "goshujin wa sushi ga suki desu ka",
    "where is your wife?": "okusan wa doko desu ka",
    "did your husband go?": "dannasan wa ikimashita ka",
    "my wife is at college": "tsuma wa daigaku ni imasu",
    "my husband won't come today": "kyou shujin wa kimasen",
    "i like that (twenty-something) girl.": "ano oneesan ga suki desu",
    "where did that old man go?": "ano ojiisan wa doko ni ikimashita ka",
    "he / boyfriend": "kare",
    "her / girlfriend": "kanojo",
    "do you have a girlfriend?": "kanojo ga imasu ka",
    "i don't like my boyfriend's mom": "kare no okaasan ga suki dewa arimasen",
    "Mariko is john's girlfriend": "Mariko san wa Jon san no kanojo desu",
    "i went to the mountains with my boyfriend last week.": "senshuu "
        "kare to yama ni ikimashita",
    "hobby": "shumi",
    "interest": "kyoumi",
    "the countryside": "inaka",
    "place": "tokoro",
    "mountain climbing": "yama no bori",
    "a drive": "doraibu",
    "hiking": "haikingu",
    "a walk": "sanpo",
    "sightseeing": "kengaku",
    "what are you interested in?": "nan ni kyoumi ga arimasu ka",
    "what kind of place is it?": "donna tokoro desu ka",
    "is it a good place?": "ii tokoro desu ka",
    "to go for a drive": "doraibu ni ikimasu",
    "welcome to": "e youkoso",
    "there you are / go ahead / after you": "douzo",
    "number": "bangou",
    "sorry, could you repeat that?": "sumimasen mou ichido itte kudasai",
    "hello (on phone)": "moshi moshi",
    "now / at the moment": "ima",
    "not at home": "rusu",
    "mobile phone": "keita denwa",
    "have you decided?": "okimari desu ka",
    "may i have?": "wo kudasai",
    "one item": "hitotsu",
    "two items": "futatsu",
    "three items": "mittsu",
    "four items": "yottsu",
    "five items": "itsutsu",
    "six items": "muttsu",
    "seven items": "nanatsu",
    "eight items": "yattsu",
    "nine items": "kokonotsu",
    "ten items": "tou",
    "delicious": "oishii",
    "also / as well": "mo",
    "i": "boku",
    "sandwitch": "sandoichi",
    "ham": "hamu",
    "cheese": "chizu",
    "coffee": "kouhii",
    "Mariko, what are your interests?": "Mariko san kyoumi wa nan desu ka",
    "in the summer, i like hiking. in the fall, i go on walks every day. I "\
            "like the countryside. how about you? what are your hobbies?":\
            "natsu wa haikingu ga suki desu. aki wa mainichi sanpo ni "\
            "ikimasu. inaka ga suki desu. anata wa shumi wa nan desu ka",
    "i like moutain climbing. i go every week.": "yama no bori ga suki desu. "\
        "maishuu ikimasu",
    "the city": "tokai",
    "movie": "eiga",
    "theater": "eigakan",
    "shopping": "kaimono",
    "coffee shop": "kissaten",
    "museum": "hakubutsukan",
    "art": "bijutsu",
    "art museum": "bijutsukan",
    "karaoke": "karaoke",
    "castle": "shiro",
    "birthday": "tanjoubi",
    "party": "paatii",
    "money": "okane",
    "hall": "kan",
    "to go shopping": "kaimono ni ikimasu",
    "science museum": "kagaku hakubutsukan",
    "science": "kagaku",
    "i don't have any money": "okane ga arimasen",
    "john doesn't have any money": "Jon san wa okane ga arimasen",
    "Mariko has money.": "Mariko san wa okane ga arimasu",
    "john, do you like the city?": "Jon san tokai ga suki desu ka",
    "yeah, i like it. i love coffee shops and karaoke.": "ee suki desu yo. "\
        "kissaten ya karaoke ga daisuki desu",
    "do you like art?": "bijutsu ga suki desu ka",
    "yeah, i like it.": "un suki desu yo",
    "shall we go to an art gallery or museum?": "bijutsukan ka hakubutsukan "\
        "ni ikimashou ka",
    "that sounds nice!": "ii desu ne",
    "music": "ongaku",
    "piano": "piano",
    "trumpet": "toranpetto",
    "sports": "supoutsu",
    "soccer": "sakkaa",
    "basketball": "basukettobouru",
    "american football": "futtobouru",
    "tennis": "tenisu",
    "baseball": "yakyuu",
    "i like the piano.": "piano ga suki desu",
    "i like sports.": "supoutsu ga suki desu",
    "john likes tennis": "Jon san wa tenisu ga suki desu",
    "top / above": "ue",
    "bottom / below": "shita",
    "right": "migi",
    "left": "hidari",
    "-side": "gawa",
    "the right side": "migigawa",
    "the left side": "hidarigawa",
    "middle / inside": "naka",
    "front / before": "soto",
    "back": "ushiro",
    "after": "ato",
    "the top of the refrigerator": "reizouko no ue",
    "the inside of the car": "kuruma no naka",
    "the right of the house": "ie no migi",
    "in front of the teacher": "sensei no soto",
    "the top of the desk": "tsukue no ue",
    "the back of the blackboard": "kokuban no ushiro",
    "after school": "gakkou no ato",
    "there's a cat in the garden": "neko ga niwa ni imasu",
    "there's a cat on top of the fridge": "neko ga reizouko no ue ni imasu",
    "there's a book on top of the bed": "hon ga beddo no ue ni arimasu",
    "there's a dog under the table": "inu ga teeburu no shita ni imasu",
    "Mariko is inside of the store": "Mariko san wa mise no naka ni imasu",
    "there's a bird above the river": "tori ga kawa no ue ni imasu",
    "there's a fish inside the river": "sakana ga kawa no naka ni imasu",
    "there's a book to the left of the desk": "hon ga tsukue no hidari ni arimasu",
    "do (*2)": "shimasu shite",
    "speak (*2)": "hanashimasu hanashite",
    "hear (*2) / ask": "kikimasu kiite",
    "write (*2)": "kakimasu kaite",
    "buy (*2)": "kaimasu katte",
    "stand (*2)": "tachimasu tatte",
    "sit (*2)": "suwarimasu suwatte",
    "understand (*2)": "wakarimasu wakatte",
    "i talk with Mariko every day": "mainichi Mariko san to hanashimasu",
    "i talked with john last week": "senshuu Jon san to hanashimashita",
    "please talk to ms. Suzuki tomorrow": "ashita Suzuki san to hanashite kudasai",
    "i listen to the radio": "rajio wo kikimasu",
    "i asked to the teacher": "sensei ni kikimashita",
    "i listened to music": "ongaku wo kikimashita",
    "i'll ask mom": "okaasan ni kikimasu",
    "i don't understand chinese": "chuugokugo ga wakarimasen",
    "math doesn't break down for me": "suugaku ga wakarimasen",
    "do you understand geography?": "chiri ga wakarimasu ka",
    "got it": "wakarimashita",
    "do you understand the roads = do you know the way?": "michi ga "\
            "wakarimasu ka",
    "way to a given location": "michi",
    "what will you do tomorrow?": "ashita nani wo shimasu ka",
    "i'll write a book": "hon wo kakimasu",
    "i'll listen to the radio": "rajio wo kikimasu",
    "let's stand in the street": "michi ni tachimashou",
    "won't you sit down in the chair?": "isu ni suwarimasen ka",
    "do you understand english?": "eigo ga wakarimasu ka",
    "i don't understand japanese": "nihongo ga wakarimasen",
    "study": "benkyou",
    "practice": "renshuu",
    "cleaning": "souji",
    "cooking": "ryori",
    "i practice piano every day": "mainichi piano wo renshuu shimasu",
    "please clean the kitchen": "daidokoro wo souji shite kudasai",
    "what will you cook today?": "kyou nani wo ryori shimasu ka",
    "john made a phone call to Mariko": "Jon san wa Mariko san ni denwa "\
        "shimashita",
    "let's study japanese": "nihongo wo benkyou shimashou",
    "did you have fun at the party?": "paatii tanoshikatta desu ka",
    "i practice tennis.": "tenisu wo renshuu shimasu",
    "Mariko practices baseball every week": "maishuu Mariko san wa yakyuu wo "\
        "renshuu shimasu",
    "john practices sport every day": "mainichi Jon san wa supoutsu wo "\
        "renshuu shimasu",
    "let's play baseball tomorrow": "ashita yakyuu wo shimashou",
    "i played soccer today": "kyou sakkaa wo shimashita",
    "are you japanese? i'm japanese, too.": "anata wa nihonjin desu ka. "\
        "watashi mo nihonjin desu",
    "there is a dog. there's also a cat": "inu ga imasu. neko mo imasu",
    "i like potatoes. i also like bread": "imo ga suki desu. pan mo suki desu",
    "i'll go on monday. i'll also go on tuesday": "getsuyoubi ni ikimasu."\
        " kayoubi ni mo ikimasu",
    "there were dogs, cats and fish": "inu mo neko mo sakana mo imashita",
    "i went to the station and to the supermarket and to the post office":
        "eki ni mo suupaamaaketto ni mo yuubinkyoku ni mo ikimashita",
    "this morning i ate breakfast. i went to school": "kesa asagohan wo "\
        "tabemashita. gakkou ni ikimashita",
    "this morning i ate breakfast, and then i went to school.": "kesa "\
        "asagohan wo tabete gakkou ni ikimashita",
    "i went to school and studied": "gakkou ni itte benkyou shimashita",
    "today i watched tv, went to college, and phoned a friend.": "kyou "\
            "terebi wo mite daigaku ni itte tomodachi ni denwa shimashita",
    "where is tokyo?": "tokyo wa doko desu ka",
    "which pencil is it?": "dono enpitsu desu ka",
    "who?": "dare",
    "who is it?": "dare desu ka",
    "who is the teacher?": "sensei wa dare desu ka",
    "who went?": "dare ga ikimashita ka",
    "who is there?": "dare ga imasu ka",
    "who ate my ice cream?": "dare ga watashi no aisukuri-mu wo tabemashita ka",
    "ice cream": "aisukuri-mu",
    "Mariko went": "Mariko san ga ikimashita",
    "john is there": "Jon san ga imasu",
    "i ate it": "watashi ga tabemashita",
    "i (do/did/am/etc)": "watashi ga",
    "Mariko (does/did/is/etc)": "Mariko san ga",
    "when?": "itsu",
    "when is it?": "itsu desu ka",
    "when is Mariko's birthday?": "Mariko san no tanjoubi wa itsu desu ka",
    "when will you go to japan?": "itsu nihon ni ikimasu ka",
    "when will you clean the room?": "itsu heya wo souji shimasu ka",
    "why?": "naze",
    "why? / how?": "doushite",
    "why? / how? (2)": "nande",
    "how?": "dou yatte",
    "why is it? how is it?": "doushite desu ka",
    "why is that?": "sore wa doushite desu ka",
    "why is it?": "naze desu ka",
    "why didn't you go to school?": "doushite gakkou ni ikimasen deshita ka",
    "why did you eat my ice cream?": "naze watashi no aisukuri-mu wo "\
        "tabemashita ka",
    "how did you read that book?": "dou yatte sono hon yomimashita ka",
    "how did you know?": "dou yatte wakarimashita ka",
    "why did the teacher go?": "doushite sensei wa ikimashita ka",
    "how did you buy that book?": "dou yatte sono hon wo kaimashita ka",
    "how many?": "ikutsu",
    "there were eight rocks": "ishi ga yattsu arimashita",
    "i ate five apples": "ringo wo itsutsu tabemashita",
    "there were three moutains": "yama ga mittsu arimashita",
    "there are two": "futatsu arimasu",
    "there are four": "yottsu arimasu",
    "there are ten": "tou arimasu",
    "how many are there?": "ikutsu arimasu ka",
    "how many rocks are there?": "ishi ga ikutsu arimasu ka",
    "one person": "hitori",
    "two people": "futari",
    "three people": "sannin",
    "four people": "yonin",
    "person counter": "nin",
    "how many people?": "nannin",
    "there was one teacher": "sensei ga hitori imashita",
    "there were thirty students": "seito ga sanjuunin imashita",
    "there were four hundred students at the school": "gakkou ni seito ga "\
        "yonhyakunin imashita",
    "how many people are there?": "nannin imasu ka",
    "how many students are there?": "seito ga nannin imasu ka",
    "how many students are there at the school?": "gakkou ni seito ga nannin "\
        "imasu ka?",
    "counter for sheets": "mai",
    "how many sheets?": "nanmai",
    "paper": "kami",
    "postal stamp": "kitte",
    "letter": "tegami",
    "please give me one sheet of paper.": "kami wo ichimai kudasai",
    "there are seven stamps.": "kitte ga nanamai arimasu",
    "how many sheets of paper are there?": "kami ga nanmai arimasu ka",
    "counter for small, roundish things": "ko",
    "one (small roundish things)": "ikko",
    "six (small roundish things)": "rokko",
    "strange": "okashi",
    "to know": "shiteimasu",
    "eight (small roundish things)": "hakko",
    "ten (small roundish things)": "jukko",
    "how many? (small roundish things)": "nanko",
    "there are three chairs": "isu ga sanko arimasu",
    "there were eleven garbage cans": "gomibako ga juuikko arimashita",
    "how many cups are there?": "koppu ga nanko arimasu ka",
    "john ate six strawberries": "Jon san wa ichigo wo rokko tabemashita",
    "i saw seven (small roundish objects)": "watashi wa nanako mimashita",
    "counter for long, cylindrical things": "hon",
    "one (long, cylindrical objects)": "ippon",
    "three (long, cylindrical objects)": "sanbon",
    "six (long, cylindrical objects)": "roppon",
    "eight (long, cylindrical objects)": "happon",
    "ten (long, cylindrical objects)": "juppon",
    "how many (long, cylindrical objects)": "nanbon",
    "please give me three pencils": "enpitsu wo sanbon kudasai",
    "there are seven roads": "michi ga nanahon arimasu",
    "i read one book": "hon wo ippon yomimashita",
    "how many pens are there?": "pen ga nanbon arimasu ka",
    "how many books did you read?": "hon wo nanbon yomimashita ka",
    "counter for animals (except birds)": "hiki",
    "one (counter for animals)": "ippiki",
    "three (counter for animals)": "sanbiki",
    "six (counter for animals)": "roppiki",
    "eight (counter for animals)": "happiki",
    "ten (counter for animals)": "juppiki",
    "How many? (counter for animals)": "nanbiki",
    "There were three cats": "neko ga sanbiki imashita",
    "There are ten rats at the station": "eki ni nezumi ga juppiki imasu",
    "rat": "nezumi",
    "How many horses did you see?": "uma wo nanbiki mimashita ka",
    "How many mice are there in the kitchen?": "daidokoro ni nezumi ga "\
        "nanbiki imasu ka",
    "o'clock / counter for hours": "ji",
    "half past": "han",
    "counter for minutes": "fun",
    "what time?": "nanji",
    "four o'clock": "yoji",
    "nine o'clock": "kuji",
    "seven o'clock": "shichiji",
    "it's nine o'clock": "kuji desu",
    "it's three o'clock": "sanji desu",
    "it's seven o'clock": "shichiji desu",
    "I went to school at seven o'clock": "shichiji ni gakkou ni ikimashita",
    "I went on a walk at four o'clock": "yoji ni sanpo ni ikimashita",
    "Let's eat dinner at five o'clock": "goji ni bangohan wo tabemashou",
    "It's half past two": "niji han desu",
    "Mr Suzuki will come at half past six": "Suzuki san wa rokuji han ni kimasu",
    "Let's go to the park at half past eight": "hachiji han ni kouen ni ikimashou",
    "one minute": "ippun",
    "two minutes": "nifun",
    "three minutes": "sanfun",
    "four minutes": "yonfun",
    "five minutes": "gofun",
    "six minutes": "roppun",
    "seven minutes": "nanafun",
    "eight minutes": "happun",
    "nine minutes": "kyuufun",
    "ten minutes": "juppun",
    "fourty-four minutes": "yonjuuyonfun",
    "eleven minutes": "juuippun",
    "twenty-eight minutes": "nijuuhappun",
    "3:29": "sanji nijuukyuufun",
    "12:31": "juuniji sanjuuippun",
    "7:30 (different from 'half past seven')": "shichiji sanjuppun",
    "I went to school at 8:20": "hachini nijuppun ni gakkou ni ikimashita",
    "The teacher will come to our house at 5:35": "goji sanjuugofun ni "\
        "sensei wa ie ni kimasu",
    "What time is it (now)?": "ima nanji desu ka",
    "a.m": "gozen",
    "p.m": "gogo",
    "from": "kara",
    "until": "made",
    "4:39 a.m": "gozen yoji sanjuukyuufun",
    "9:10 pm": "gogo kuji juppun",
    "11:59 a.m": "gozen juuichiji gojuukyuufun",
    "from half past eight a.m to 5:40 p.m": "gozen hachiji han kara gogo "\
        "goji yonjuppun made",
    "blue": "aoi",
    "white": "shiroi",
    "green": "midori",
    "black": "kuroi",
    "red": "akai",
    "yellow": "kiiroi",
    "from 12:00 p.m. to 2:00 a.m.": "gogo juuniji kara gozen niji made",
    "the first of the month": "tsuitachi",
    "the second of the month": "futsuka",
    "the third of the month": "mikka",
    "the fourth of the month": "yokka",
    "the fifth of the month": "itsuka",
    "the sixth of the month": "muika",
    "the seventh of the month": "nanoka",
    "the eighth of the month": "youka",
    "the ninth of the month": "kokonoka",
    "the tenth of the month": "touka",
    "the fourteenth of the month": "juuyokka",
    "the twentieth of the month": "hatsuka",
    "the twentyfourth of the month": "nijuuyokka",
    "counter for other days of the month": "nichi",
    "what day of the month": "nannichi",
    "January 1st": "ichigatsu tsuitachi",
    "October 14th": "juugatsu juuyokka",
    "August 30th": "hachigatsu sanjuunichi",
    "December 20th": "juunigatsu hatsuka",
    "What day of the month is it?": "nannichi desu ka",
    "What is the month and date?": "nangatsu nannichi desu ka",
    "counter for years": "nen",
    "what year?": "nannen",
    "One year": "ichinen",
    "Ten years": "juunen",
    "Five hundred years": "gohyakunen",
    "February 3rd, 1974": "senkyuuhyakunanajuuyonen nigatsu mikka",
    "September 9th, 2000": "nisennen kugatsu kokonoka",
    "December 14th, 2010": "nisenjuunen juunigatsu juuyokka",
    "March 20th, 2500": "nisengohyakunen sangatsu hatsuka",
    "counter for age": "sai",
    "one year old": "issai",
    "eight years old": "hassai",
    "ten years old": "jussai",
    "twenty years old": "hatachi",
    "how many years old?": "nansai",
    "how many years old? (polite)": "oikutsu",
    "How old are you?": "anata wa nansai desu ka",
    "I'm 21": "nijuuissai desu",
    "I'm 65": "rokujuugosai desu",
    "John is 25": "Jon san wa nijuugosai desu",
    "How old is Mariko?": "Mariko san wa nansai desu ka",
    "Mariko is 20 years old": "Mariko san wa hatachi desu",
    "counter for yen": "en",
    "bill": "satsu",
    "coin": "dama",
    "How much money / cost?": "ikura",
    "100 yen": "hyakuen",
    "5000 yen": "gosenen",
    "10,000 yen": "ichimanen",
    "How much is this?": "kore wa ikura desu ka",
    "It's 800 yen": "happyakuen desu",
    "Really? How much is this?": "sou desu ka. kore wa ikura desu ka",
    "That is 1200 yen": "sore wa sennihyakuen desu",
    "How much is this radio?": "kono rajio wa ikura desu ka",
    "It's 2500 yen": "nisengohyakuen desu",
    "Mariko, look at this": "Mariko san kore wo mite",
    "What is it?": "nan desu ka",
    "It's a plate. I wonder if I should buy it": "sara desu. kaimashou ka ne",
    "How much is it?": "ikura desu ka",
    "Um... It's 3000 yen": "ee to sanzenen desu",
    "This one is 2000 yen": "kore wa nisenen desu yo",
    "Oh, that's good": "a sore ga ii desu ne",
    "Are you going to buy it?": "kaimasu ka",
    "Yeah, I think I'll buy three. What are you going with?": "un kono sara "\
        "wo sanmai kaimashou. Mariko san wa nan ni shimasu ka",
    "This sake is 1500 yen. I think I'll buy three bottles for my father":
        "kono sake wa sengohyakuen desu. chichi ni sanbon kaimashou",
    "How old is your father?": "otousan wa oikutsu desu ka",
    "He's 47. His birthday was last month": "yonjuunanasai desu. sengetsu ga "\
        "tanjoubi deshita",
    "Oh, what time is it now?": "a ima nanji desu ka",
    "It's 3:35. This store is open until 5:00": "sanji sanjuugofun desu. "\
        "kono mise wa goji made desu",
    "Then we have time, don't we?": "ja jikan ga arimasu ne",
    "time": "jikan"
    "But...": "demo",
    "However...": "shikashi",
    "...but": "ga",
    "...but (2)": "keredomo",
    "...but (3)": "keredo",
    "...but (4)": "kedo",
    "But I don't like sushi": "demo sushi ga suki dewa arimasen",
    "However the teacher isn't here": "shikashi sensei wa imasen",
    "But I didn't go to the station": "demo eki ni ikimasen deshita",
    "I went to school, but the teacher wasn't there": "gakkou ni ikimashita "\
        "ga sensei wa imasen deshita",
    "John went to college, but he didn't study": "Jon san wa daigaku ni "\
        "ikimashita kedo benkyou shimasen deshita",
    "I don't like history, but I love geography": "rekishi ga suki dewa "
        "arimasen keredomo chiri ga daisuki desu",
    "history": "rekishi",
    "It's blue-green": "aoi desu",
    "It's white": "shiroi desu",
    "The dog is black": "inu wa kuroi desu",
    "Apples are red": "ringo wa akai desu",
    "The sky is blue": "sora wa aoi desu",
    "It's a black dog": "kuroi inu desu",
    "It's a red apple": "akai ringo desu",
    "It's a blue sky": "aoi sora desu",
    "This is a white cat": "kore wa shiroi neko desu",
    "That is a blue car": "are wa aoi kuruma desu",
    "That is a yellow pencil": "sore wa kiiroi enpitsu desu",
    "This is not a white garbage can": "kore wa shiroi gomibako dewa arimasen",
    "That was John's black book": "sore wa Jon san no kuroi hon deshita",
    "purple": "murasaki",
    "color": "iro",
    "brown": "chairo",
    "orange (color)": "orenjiiro",
    "grey": "nezumiiro",
    "It's a purple dish": "murasaki no sara desu",
    "I like green pencils": "midori no enpitsu ga suki desu",
    "I saw a brown car": "chairo no kuruma wo mimashita",
    "Hanako is an orange cat": "Hanako chan wa orenjiiro no neko desu",
    "good (skilled)": "jouzu",
    "bad (unskilled)": "heta",
    "strange / weird": "hen",
    "clean / pretty": "kirei",
    "simple": "kantan",
    "likeable": "suki",
    "disagreeable": "kirai",
    "A skilled teacher": "jouzu na sensei",
    "A strange person": "hen na hito",
    "A simple test": "kantan na tesuto",
    "test": "tesuto",
    "A likeable movie (that is, a movie that I like)": "suki na eiga",
    "Mariko, is there a person you like?": "Mariko san suki na hito ga imasu ka",
    "This is a strange food, isn't it?": "kore wa hen na tabemono desu ne",
    "Mr. Suzuki is a bad teacher, isn't he?": "Suzuki san wa heta na sensei "\
        "desu ne",
    "My cat is black": "watashi no neko wa kuroi",
    "The walls of the bathroom were red": "toire no kabe wa akakatta",
    "That flower was not white": "sono hana wa shirokunakatta",
    "The sky was blue": "sora wa aokatta",
    "The water is not blue": "mizu wa aokunai",
    "was good": "yokatta",
    "not good": "yokunai",
    "wasn't good": "yokunakatta",
    "hot": "atsui",
    "hot and humid": "mushi atsui",
    "cold (air)": "samui",
    "cold to the touch": "tsumetai",
    "warm": "atatakai",
    "cool": "suzushii",
    "non-existant": "nai",
    "I have no money": "okane ga nai",
    "I had no money": "okane ga nakatta",
    "It's not me": "watashi dewa nai",
    "it wasn't you": "anata dewa nakatta",
    "It's hot weather today, isn't it?": "kyou wa atsui otenki desu ne",
    "It sure is. And it was cool up until yesterday!": "sou desu ne. kinou "\
        "made suzushikatta noni ne",
    "When is your favorite season?": "anata no ichiban suki na kisetsu wa "\
        "itsu desu ka",
    "season": "kisetsu",
    "I like the fall": "aki ga suki desu ne",
    "Really? I like the hot weather of summer": "sou desu ka. watashi wa "\
        "natsu no atsui tenki ga suki desu",
    "You're a weird one, aren't you? I like the cool weather of fall": "hen "\
        "na hito desu ne. watashi wa aki no suzushii otenki ga suki desu",
    "don't worry": "mondainashi",
    "tall / expensive": "takai",
    "low / short (in height)": "hikui",
    "cheap": "yasui",
    "wide / spacious": "hiroi",
    "narrow / cramped": "semai",
    "big": "ookii",
    "small": "chiisai",
    "bad": "warui",
    "good (ancient form)": "yoi",
    "long": "nagai",
    "short (in length)": "mijikai",
    "a tall mountain": "takai yama",
    "a low cloud": "hikui kumo",
    "a cheap book": "yasui hon",
    "a wide park": "hiroi kouen",
    "a narrow house": "semai ie",
    "This car was expensive": "kono kuruma wa takakatta",
    "My room is not big": "watashi no heya wa hirokunai",
    "The teacher's desk is short (low to the ground)": "sensei no tsukue wa"\
        " hikui",
    "bland": "mazui",
    "beautiful": "utsukushii",
    "ugly": "minikui",
    "quiet": "shizuka",
    "noisy": "urusai",
    "strong": "tsuyoi",
    "weak": "yowai",
    "tasty": "oishii",
    "This is delicious cooking, isn't it?": "kore wa oishii ryori desu ne",
    "This beer is disgusting": "kono biiru wa mazui",
    "The woman over there is beautiful": "osoko no onna no hito wa utsukushii",
    "There is an ugly house over there.": "osoko ni minikui ie ga arimasu",
    "John's radio is noisy. I don't like it.": "Jon san no rajio wa urusai. "
        "suki dewa nai",
    "happy": "ureshii",
    "sad": "kanashii",
    "fun": "tanoshii",
    "boring": "tsumaranai",
    "cool / awesome / incredible": "sugoi",
    "dirty": "itanai",
    "difficult": "muzukashii",
    "easy / friendly": "yasashii",
    "stern": "kibishii",
    "fast / early": "hayai",
    "slow / late": "osoi",
    "a lot": "ippai",
    "I was happy": "watashi wa ureshikatta",
    "Mariko is sad": "Mariko san wa kanashii",
    "Yesterday was fun": "kinou wa tanoshikatta",
    "Tomorrow will be fun, won't it?": "ashita wa tanoshii deshou ne",
    "That's awesome!": "sore wa sugoi",
    "I'm going to cook tonight": "konban watashi wa ryori shimasu",
    "Wow! What are you going to cook?": "sugoi. nani wo ryori shimasu ka",
    "Fish. Do you like (that)?": "sakana. suki desu ka",
    "Yes, I do (like it). Was it expensive?": "suki desu yo. takakatta desu ka",
    "No, it was cheap. But it should be good": "iie yasukatta. demo oishii deshou",
    "This fish is big, isn't it! You cooked this? (to John)": "kono sakana wa ookii "\
        "desu ne. kore Jon san ga ryori shimashita ka",
    "That's right": "sou desu yo",
    "You're talented, aren't you? It's delicious!": "jouzu desu ne. oishii",
    "Oh, I'm happy (to hear that). Eat lots!": "aa ureshii. ippai tabete kudasai",
    "head": "atama",
    "forehead": "hitai",
    "face": "kao",
    "eye": "ne",
    "nose": "hana",
    "mouth": "kuchi",
    "tooth": "ha",
    "tongue": "shita",
    "ear": "mimi",
    "cheek": "hoho",
    "American people have big noses, but Japanese people have small ones": 
        "amerikajin wa hana ga takai kedo nihonjin wa hana ga hikui",
    "neck": "kubi",
    "shoulder": "kata",
    "chest": "mune",
    "arm": "ude",
    "elbow": "hiji",
    "hand": "te",
    "wrist": "tekubi",
    "finger": "yubi",
    "finger (nail)": "tsume",
    "fat": "futoi",
    "slender": "hosoi",
    "to wait": "mattemasu",
}


class Question:
    """Object for a question"""

    def __init__(self, question, answer, success, failure, index):
        self.question = question
        self.answer = answer
        self.success = success
        self.failure = failure
        self.index = index

    def verify(self, answer):
        if self.answer == answer:
            self.success += 1
        else:
            self.failure += 1
        self.update_db()

    def update_db(self):
        vocab_file = open("vocabulary.txt", "w+")
        vocab_file.writelines(vocab)
        vocab_file.close()


def init():
    """At the first execution, we create a new file, where we'll add the scores
    for each sentence"""
    if not os.path.exists("vocabulary.txt"):
        vocab_file = open("vocabulary.txt", "a")
        for en_sentence, jp_sentence in vocabulary.iteritems():
            vocab_file.write("%s|%s|0|0\n" % (en_sentence, jp_sentence))
        vocab_file.close()


def question(vocab):
    line = random.choice(vocab)
    question, answer, success, failure = line.split("|")
    success = int(success)
    failure = int(failure.replace("\n", ""))
    guess = raw_input("%s (found:%s, failed:%s)\n\t%s\n%s " %
                      (colored("Question", "blue"),
                       colored(success, "green"),
                       colored(failure, "red"),
                       question,
                      colored("Answer :", "blue")))
    if guess == "x":
        return
    elif guess == answer:
        response = colored(random.choice(["Yes", "Good", "Perfect",
                                          "Congrats", "いい"]), "green")
        success += 1
    else:
        response = colored("False, the answer was '%s'" %
                           vocabulary[question], "red")
        failure += 1
    line_index = vocab.index(line)
    vocab.remove(line)
    vocab.insert(line_index, "%s|%s|%s|%s\n" % (question, answer, success,
                                                failure))
    return response


if __name__ == "__main__":
    init()
    vocab = open("vocabulary.txt").readlines()
    while 1:
        answer = question(vocab)
        if not answer:
            break
        else:
            print answer

    print "%s\nBye !%s\n" % ("~" * 10, "~" * 10)

    try:
        vocab_file = open("vocabulary.txt", "w+")
        vocab_file.writelines(vocab)
        vocab_file.close()
    except IOError, e:
        print "Couldn't save the file\n%s" % e
