#-*- coding:utf-8 -*-
'''
Learn vocabulary

Currently a console program, don't forget to install termcolor
'''

import os.path
import random
from termcolor import colored


vocabulary = {
    "Good morning": "ohayou gozaimasu",
    "Good afternoon": "konnichi wa",
    "Good evening": "konban wa",
    "Goodnight": "oyasumi nasai",
    "Thank you very much": "doumo arigatou gozaimasu",
    "Thank you": "arigatou gozaimasu",
    "Thanks": "arigatou",
    "Cheers!": "doumo",
    "Thank you very much": "doumo arigatou gozaimasu",
    "You're welcome": "dou itashimashite",
    "Nice to meet you (in beginning)": "hajimemashite",
    "Nice to meet you (thanks in advance)": "douzo yoroshiku",
    "I'm ~": "desu",
    "bow": "ojigi",
    "(your) name": "onamae",
    "What is your name?": "onamae wa nan desu ka",
    "How are you?": "ogenki desu ka",
    "I'm well": "genki desu",
    "yes": "hai",
    "no": "iie",
    "Japan": "nihon",
    "America": "amerika",
    "Canada": "kanada",
    "A person from ~": "jin",
    "Japanese person": "nihon-jin",
    "American person": "amerika-jin",
    "dog": "inu",
    "cat": "neko",
    "apple": "ringo",
    "water": "mizu",
    "bird": "tori",
    "horse": "uma",
    "pencil": "enpitsu",
    "pen": "pen",
    "is/are/am": "desu",
    "it will be": "deshou",
    "isn't": "dewa arimasen",
    "was": "deshita",
    "wasn't": "dewa arimasen deshita",
    "house": "ie",
    "room": "heya",
    "living room": "ima",
    "kitchen": "daidokoro",
    "refrigerator": "reizouko",
    "bathroom (polite)": "otearai",
    "bathroom": "toire",
    "sink": "nagashidai",
    "bath": "ofuro",
    "bath-room": "ofuroba",
    "roof": "yane",
    "ceiling": "tenjou",
    "wall": "kabe",
    "hardwood floor": "yuka",
    "door": "doa",
    "window": "mado",
    "bookshelf": "hondana",
    "chair": "isu",
    "bed": "beddo",
    "tatami": "tatami",
    "sliding paper door": "shouji",
    "futon": "futon",
    "TV": "terebi",
    "radio": "rajio",
    "clock/watch": "tokei",
    "air conditioning": "eakon",
    "plate": "sara",
    "bowl": "chawan",
    "cup": "koppu",
    "glass": "garasu",
    "chopsticks": "ohashi",
    "fork": "houku",
    "spoon": "supuun",
    "knife": "naifu",
    "table": "teeburu",
    "couch": "kauchi",
    "computer": "konpyuutaa",
    "one": "ichi",
    "two": "ni",
    "three": "san",
    "four": "yon",
    "five": "go",
    "six": "roku",
    "seven": "nana",
    "eight": "hachi",
    "nine": "kyuu",
    "ten": "juu",
    "one hundred": "hyaku",
    "two hundred": "ni-hyaku",
    "three hundred": "san-byaku",
    "four hundred": "yon-hyaku",
    "five hundred": "go-hyaku",
    "six hundred": "roppyaku",
    "seven hundred": "nana-hyaku",
    "eight hundred": "happyaku",
    "nine hundred": "kyuu-hyaku",
    "one thousand": "sen",
    "two thousand": "ni-sen",
    "three thousand": "san-zen",
    "four thousand": "yon-sen",
    "five thousand": "go-sen",
    "six thousand": "roku-sen",
    "seven thousand": "nana-sen",
    "eight thousand": "hassen",
    "nine thousand": "kyuu-sen",
    "ten thousand": "man",
    "one hundred million": "oku",
    "today": "kyou",
    "yesterday": "kinou",
    "tomorrow": "ashita",
    "the day before yesterday": "ototoi",
    "the day after tomorrow": "asatte",
    "this morning": "kesa",
    "night": "yoru",
    "last night": "yuube",
    "Sunday": "nichiyoubi",
    "Monday": "getsuyoubi",
    "Tuesday": "kayoubi",
    "Wednesday": "suiyoubi",
    "Thursday": "mokuyoubi",
    "Friday": "kin'youbi",
    "Saturday": "doyoubi",
    "last week": "senshuu",
    "this week": "konshuu",
    "next week": "raishuu",
    "the week before last week": "sensenshuu",
    "the week after next week": "saraishuu",
    "last month": "sengetsu",
    "this month": "kongetsu",
    "next month": "raigetsu",
    "the month before last": "sensengetsu",
    "the month after next": "saraigetsu",
    "suffix for month of year": "gatsu",
    "January": "ichi-gatsu",
    "February": "ni-gatsu",
    "March": "san-gatsu",
    "April": "shi-gatsu",
    "July": "shichi-gatsu",
    "September": "ku-gatsu",
    "last year": "kyonen",
    "this year": "kotoshi",
    "next year": "rainen",
    "the year before last": "ototoshi",
    "the year after next": "sarainen",
    "every- prefix": "mai",
    "every day": "mainichi",
    "every week": "maishuu",
    "every month": "maitsuki",
    "every year": "maitoshi",
    "winter": "fuyu",
    "spring": "haru",
    "summer": "natsu",
    "autumn": "aki",
    "good": "ii",
    "weather": "otenki",
    "park": "kouen",
    "(agreement seeker)": "ne",
    "I'm leaving!": "itte kimasu",
    "See you when you get home!": "itterasshai",
    "I'm home!": "tadaima",
    "Welcome back!": "okaeri nasai",
    "Good night.": "oyasumi nasai",
    "I'm sorry.": "sumimasen",
    "Excuse me.": "shitsurei shimasu",
    "goodbye": "sayonara",
    "well then...": "dewa",
    "See you later": "ja mata",
    "Later!": "mata ne",
    "See ya": "jaa ne",
    "They're chopsticks": "ohashi desu",
    "Are they chopsticks?": "ohashi desu ka",
    "It was a dog": "inu deshita",
    "Was it a dog?": "inu deshita ka",
    "She's not Japanese": "nihon-jin dewa arimasen",
    "Isn't she Japanese?": "nihon-jin dewa arimasen ka",
    "You are American": "amerika-jin desu",
    "Are you American?": "amerika-jin desu ka",
    "that way / so": "sou",
    "It is so / That's so / Yes": "sou desu",
    "Is that so?": "sou desu ka",
    "Oh, is that so?": "aa sou desu ka",
    "Oh, really?": "aa sou",
    "what": "nan",
    "what (alternative form)": "nani",
    "what day of the week": "nan-youbi",
    "what month?": "nan-gatsu",
    "What is it?": "nan desu ka",
    "What day is it?": "nan-youbi desu ka",
    "It's Sunday": "nichiyoubi desu",
    "What month is it?": "nan-gatsu desu ka",
    "It's July.": "shichi-gatsu desu",
    "store / shop": "mise",
    "restaurant": "resutoran",
    "supermarket": "suupaamaaketto",
    "supermarket (abbreviated form)": "suupaa",
    "post office": "yuubinkyoku",
    "train station": "eki",
    "convenience store": "conbini",
    "police box": "kouban",
    "bank": "ginkou",
    "store suffix": "ya",
    "bookstore": "hon-ya",
    "bread": "pan",
    "bread store (bakery)": "pan-ya",
    "person who works at store": "yasan",
    "bookseller": "hon-yasan",
    "tree": "ki",
    "grass": "kusa",
    "flower": "hana",
    "river": "kawa",
    "lake": "misuumi",
    "mountain": "yama",
    "sky": "sora",
    "sun": "taiyou",
    "cloud": "kumo",
    "rain": "ame",
    "bicycle": "jitensha",
    "motorized cycle": "baiku",
    "automatic bicycle (motorcycle)": "outobai",
    "car": "kuruma",
    "taxi": "takushii",
    "bus": "basu",
    "bus stop": "basu tei",
    "train": "densha",
    "subway": "chikatetsu",
    "road": "mira",
    "I / me": "watashi",
    "you": "anata",
    "friend": "tomodachi",
    "person": "hito",
    "that person / he / she": "sono shito",
    "pluralizer": "tachi",
    "polite name suffix": "san",
    "teacher": "sensei",
    "the teachers": "sensei-tachi",
    "we": "watashi-tachi",
    "you (plural)": "anata-tachi",
    "people": "hito-tachi",
    "January is winter": "ichi-gatsu wa fuyu desu",
    "July is summer, isn't it?": "shichi-gatsu wa natsu desu ne",
    "I am John": "watashi wa Jon desu",
    "The name is Suzuki": "namae wa Suzuki desu",
    "Is today Thursday?": "kyou wa mokuyoubi desu ka",
    "Is March winter?": "san-gatsu wa fuyu desu ka",
    "Am I a cat?": "watashi wa neko desu ka",
    "Are you American?": "anata wa amerika-jin desu ka",
    "food": "tabemono",
    "japanese food": "washoku",
    "western food": "yoshoku",
    "sushi": "sushi",
    "unadorned raw fish": "sashimi",
    "japanese horseradish": "wasabi",
    "soy sauce": "shouyu",
    "tempura": "tenpura",
    "vinegar": "su",
    "skewered chicken": "yakitori",
    "chicken": "chikin",
    "fish": "sakana",
    "vegetables": "yasai",
    "potato": "imo",
    "tomato": "tomato",
    "lettuce": "retasu",
    "corrot": "ninjin",
    "garlic": "ninniku",
    "green onion": "negi",
    "onion": "tamanegi",
    "egg": "tamago",
    "fruit": "kudamono",
    "red grape": "pudou",
    "green grape": "masukanito",
    "lemon": "remon",
    "orange": "orengi",
    "nectarine": "mikan",
    "asian pear": "nashi",
    "strawberry": "ichigo",
    "watermelon": "suika",
    "fast food": "fasuto fuudo",
    "ground beef": "hanbaagu",
    "hamburger": "hanbaagaa",
    "French fries": "furai poteto",
    "McDonald's": "makudonarudo",
    "Mos Burger": "mosubaagaa",
    "beverage": "nomimono",
    "milk": "gyuunyuu",
    "milkshake": "migukusenki",
    "orange juice": "orenji juusu",
    "lemonade": "lemonedo",
    "sake": "sake",
    "beer": "biiru",
    "wine": "wain",
    "morning": "asa",
    "noon": "hiru",
    "evening": "ban",
    "rice": "gohan",
    "meal": "shokuji",
    "breakfast": "asagohan",
    "lunch": "hirugohan",
    "dinner": "bangohan",
    "like": "suki",
    "dislike": "kirai",
    "love (big like)": "daisuki",
    "hate (big dislike)": "daikirai",
    "I like ~": "ga suki desu",
    "I dislike ~": "ga kirai desu",
    "number one": "ichiban",
    "My favorite is ~": "ga ichiban suki desu",
    "I like hamburgers": "watashi wa hanbaagaa ga suki desu",
    "Mariko dislikes sushi": "Mariko wa sushi ga kirai desu",
    "I don't like chiken": "chikin ga suki dewa arimasen",
    "Don't you like beer?": "biiru ga suki dewa arimasen ka",
    "I liked Japan": "nihon ga suki deshita",
    "I hate carrots!": "ninjin ga daikirai desu",
    "I really like you!": "anata ga daisuki desu",
    "I like vegetables": "Yasai ga suki desu",
    "I like carrots the best": "ninjin ga ichiban suki desu",
    "I like fruits": "kudamono ga suki desu",
    "I like strawberries the most": "ichigo ga ichiban suki desu",
    "I dislike vegetables": "yasai ga kirai desu",
    "I hate onions the worst": "tamanegi ga ichiban kirai desu",
    "I dislike the winter": "fuyu ga kirai desu",
    "I hate February the most": "ni-gatsu ga ichiban kirai desu",
}


def init():
    """At the first execution, we create a new file, where we'll add the scores
    for each sentence"""
    if not os.path.exists("vocabulary.txt"):
        vocab_file = open("vocabulary.txt", "a")
        for en_sentence, jp_sentence in vocabulary.iteritems():
            vocab_file.write("%s|%s|0|0\n" % (en_sentence, jp_sentence))
        vocab_file.close()


def question(vocab):
    line = random.choice(vocab)
    question, answer, success, failure = line.split("|")
    success = int(success)
    failure = int(failure.replace("\n", ""))
    guess = raw_input("%s (found:%s, failed:%s)\n\t%s\n%s " %
                      (colored("Question", "blue"),
                       colored(success, "green"),
                       colored(failure, "red"),
                       question,
                      colored("Answer :", "blue")))
    if guess == "x":
        return
    elif guess == answer:
        response = colored(random.choice(["Yes", "Good", "Perfect",
                                          "Congrats", "いい"]), "green")
        success += 1
    else:
        response = colored("False, the answer was '%s'" %
                           vocabulary[question], "red")
        failure += 1
    line_index = vocab.index(line)
    vocab.remove(line)
    vocab.insert(line_index, "%s|%s|%s|%s\n" % (question, answer, success,
                                                failure))
    return response


if __name__ == "__main__":
    init()
    vocab = open("vocabulary.txt").readlines()
    while 1:
        answer = question(vocab)
        if not answer:
            break
        else:
            print answer

    print "%s\nBye !%s\n" % ("~" * 10, "~" * 10)

    try:
        vocab_file = open("vocabulary.txt", "w+")
        vocab_file.writelines(vocab)
        vocab_file.close()
    except IOError, e:
        print "Couldn't save the file\n%s" % e
